package com.yuankui.web.controller;


import com.yuankui.web.entity.Task;
import com.yuankui.web.repository.TaskRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;


@Controller    // This means that this class is a Controller
@RequestMapping(path = "/task") // This means URL's start with /demo (after Application path)
public class TaskController {

  @Autowired // This means to get the bean called taskRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private TaskRepository taskRepository;

  @PostMapping(path = "/add") // Map ONLY GET Requests
  public String addNewTask(@RequestParam String name, @RequestParam String body) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Task n = new Task();
    n.setName(name);
    n.setBody(body);
    taskRepository.save(n);
    return "redirect:/task/all";
  }

  @GetMapping(path = "/")
  public String getAllTasks(Model model) {
    // This returns a JSON or XML with the tasks
    Iterable<Task> tasks = taskRepository.findAll();
    model.addAttribute("tasks", tasks);
    return "task/list";
  }

  @GetMapping(path = "/edit")
  public String editTask() {
    return "task/form";
  }
}